package com.hrm.hrmsystem.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * LEAVE LEDGER — Computed/Generated Table (Separation of source vs calculated data)
 *
 * Source tables  : attendance (absences), leaves (approved leave requests)
 * Calculated table: leave_ledger (this) — stores sequential balance consumption result
 *
 * This table is ALWAYS re-generated by LeaveRecalculationService.
 * Never update this directly. Use LeaveRecalculationService.recalculateFromDate().
 *
 * Design principles:
 *  - One row per event (each absence day or each leave request)
 *  - Sorted by event_date ASC in queries
 *  - running_balance always reflects state AFTER this event
 *  - paid + unpaid = requested_days (invariant)
 */
@Entity
@Table(name = "leave_ledger", indexes = {
    @Index(name = "idx_ledger_emp_date", columnList = "employee_id, event_date")
})
public class LeaveLedger {

    public enum EventType {
        ABSENT_FULL,    // Full-day manual absence
        ABSENT_HALF,    // Half-day manual absence
        APPROVED_LEAVE  // Approved leave request
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "employee_id", nullable = false)
    private Long employeeId;

    @Column(name = "event_date", nullable = false)
    private LocalDate eventDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "event_type", nullable = false, length = 20)
    private EventType eventType;

    /**
     * Reference to the source record:
     * - For ABSENT_*: attendance.id
     * - For APPROVED_LEAVE: leaves.id
     */
    @Column(name = "reference_id")
    private Long referenceId;

    /** Total days requested (1.0 for full day, 0.5 for half day) */
    @Column(name = "requested_days", nullable = false, precision = 5, scale = 1)
    private BigDecimal requestedDays;

    /** Days consumed from paid balance */
    @Column(name = "paid_days", nullable = false, precision = 5, scale = 1)
    private BigDecimal paidDays;

    /** Days counted as unpaid (requestedDays - paidDays) */
    @Column(name = "unpaid_days", nullable = false, precision = 5, scale = 1)
    private BigDecimal unpaidDays;

    /** Running paid balance AFTER this event is applied */
    @Column(name = "running_balance", nullable = false, precision = 5, scale = 1)
    private BigDecimal runningBalance;

    @Column(name = "calculated_at", nullable = false)
    private LocalDateTime calculatedAt;

    // ─── Constructors ───────────────────────────────────────────────────────────

    public LeaveLedger() {}

    public LeaveLedger(Long employeeId, LocalDate eventDate, EventType eventType,
                       Long referenceId, BigDecimal requestedDays,
                       BigDecimal paidDays, BigDecimal unpaidDays, BigDecimal runningBalance) {
        this.employeeId = employeeId;
        this.eventDate = eventDate;
        this.eventType = eventType;
        this.referenceId = referenceId;
        this.requestedDays = requestedDays;
        this.paidDays = paidDays;
        this.unpaidDays = unpaidDays;
        this.runningBalance = runningBalance;
        this.calculatedAt = LocalDateTime.now();
    }

    // ─── Getters & Setters ───────────────────────────────────────────────────────

    public Long getId() { return id; }
    public Long getEmployeeId() { return employeeId; }
    public LocalDate getEventDate() { return eventDate; }
    public EventType getEventType() { return eventType; }
    public Long getReferenceId() { return referenceId; }
    public BigDecimal getRequestedDays() { return requestedDays; }
    public BigDecimal getPaidDays() { return paidDays; }
    public BigDecimal getUnpaidDays() { return unpaidDays; }
    public BigDecimal getRunningBalance() { return runningBalance; }
    public LocalDateTime getCalculatedAt() { return calculatedAt; }

    public void setId(Long id) { this.id = id; }
    public void setEmployeeId(Long employeeId) { this.employeeId = employeeId; }
    public void setEventDate(LocalDate eventDate) { this.eventDate = eventDate; }
    public void setEventType(EventType eventType) { this.eventType = eventType; }
    public void setReferenceId(Long referenceId) { this.referenceId = referenceId; }
    public void setRequestedDays(BigDecimal requestedDays) { this.requestedDays = requestedDays; }
    public void setPaidDays(BigDecimal paidDays) { this.paidDays = paidDays; }
    public void setUnpaidDays(BigDecimal unpaidDays) { this.unpaidDays = unpaidDays; }
    public void setRunningBalance(BigDecimal runningBalance) { this.runningBalance = runningBalance; }
    public void setCalculatedAt(LocalDateTime calculatedAt) { this.calculatedAt = calculatedAt; }
}
